- Examples/FolioReaderKit.podspec.json
- IntegrationTests/GoldMaster/FolioReaderKit.podspec.json.goldmaster
- IntegrationTests/README.md
- Sources/PodToBUILD/GlobUtils.swift
- Sources/PodToBUILD/ObjcLibrary.swift
Allow all file types for resources, and parse them as globs. Previously, we didn't parse out the globs.
Additionally, I added output testing for Folio
> Add wildcard glob parsing

- BUILD
- IntegrationTests/GoldMaster/FolioReaderKit.podspec.json.goldmaster
- Makefile
- WORKSPACE
- tools/bazelwrapper
This patch adds the ability to build with Bazel. We much prefer Bazel
due to its stability, reproducibility, and nix friendliness.
> Use Bazel for release builds / update_pods.py

- BazelExtensions/extensions.bzl
- Sources/PodToBUILD/BuildFile.swift
- Sources/RepoToolsCore/RepoActions.swift
- Use //Vendor/rules_pods since we expect installation to happen there
- Remove default value for "value" in acknowledgements macros since we
generate specific paths
> Changes necessary to get acknowledgements working

- Sources/PodToBUILD/BuildFile.swift
- Sources/PodToBUILD/ObjcLibrary.swift
- Sources/PodToBUILD/ShellContext.swift
- Sources/RepoToolsCore/RepoActions.swift
Due to calling `ln` via our shell bridge cannot handle symlinking boost headers we should move to use `FileManager`
- Use FileManager API for creating symbolic links
- Prefer `.podspec.json` in advance of `.podspec`
- Small cleanup
> Use FileManager API for creating symbolic links

- Sources/PodToBUILD/XCConfig.swift
Previously we built ontop of Bazel's WORKSPACE rules and external. This
is a missed opportunity from that refactor.
> Use Vendor instead of external for XCConfig Transform

- .travis.yml
- Gemfile
- Makefile
- Package.swift
- Sources/PodToBUILD/ShellContext.swift
- Sources/RepoToolsCore/RepoActions.swift
- Tests/BuildTests/BuildTest.swift
- Tests/BuildTests/Examples/PINRemoteImage/Pods.WORKSPACE
This patch adds end to end testing for PodToBUILD.
We want to be certian, that a given Pod can build end to end.
Process:
0) Install Bazel onto host.
1) Setup a test workspace.
2) Copy over the Pods.WORKSPACE for the given example case.
3) Run bazel and check output.
It instruments the first example for PINRemoteImage as an example, more
to come soon.
> Setup end to end testing

- Examples/Folly.podspec.json
- Examples/boost-for-react-native.podspec.json
- Examples/glog.podspec.json
- IntegrationTests/GoldMaster/Folly.podspec.json.goldmaster
- IntegrationTests/GoldMaster/KakaoOpenSDK.podspec.json.goldmaster
- IntegrationTests/GoldMaster/OnePasswordExtension.podspec.json.goldmaster
- IntegrationTests/GoldMaster/React-0.57.0.podspec.json.goldmaster
- IntegrationTests/GoldMaster/Texture.podspec.json.goldmaster
- IntegrationTests/GoldMaster/boost-for-react-native.podspec.json.goldmaster
- IntegrationTests/GoldMaster/glog.podspec.json.goldmaster
- Sources/PodToBUILD/ObjcLibrary.swift
- Sources/PodToBUILD/RuleUtils.swift
- Tests/PodToBUILDTests/BuildFileTests.swift
This aliases the root lib to the pod name if it isn't already using that
name. This gives the user more flexibility in setting up their project.
Additionally add a few examples of react-native pods that triggered edge
cases.
> Alias targets to pod name / cleanups

- Examples/README.md
- Makefile
- README.md
This PR defaults the docs to the `repository_rule` as that is the
idiomatic way to install pods in Bazel. It adds notes about using
`repository_rule`s, why `PodToBUILD` supports out of band dependency
installation, and how to `bazel run` the pod updates.
Generally, it isn't ideal to do source builds of programs like
`PodToBUILD` on a users machine for performance and build environment
coupling. This PR defaults documentation to point at binary releases.
Fixes #36
> Docs for bazel run, FAQ, repository_rule, installs

- Sources/PodToBUILD/ShellContext.swift
Fix mistake for adding `%` before `$PATH`
> shellcontext: fix wrong env path

- BUILD
- Sources/PodToBUILD/ShellContext.swift
- WORKSPACE
- tools/bazelwrapper
I had some trouble getting `PodToBUILD` working on my local setup running the latest versions of Bazel, `rules_swift`, and `rules_apple`, so I'm PR'ing the changes I made to get everything copacetic.
- `@build_bazel_rules_apple//apple:swift.bzl` no longer exists
- Throughout the tooling, some shell variables aren't appropriately quoted. I have some spaces in my `$PATH`, so I addressed all the places this was causing a problem.
- ~(optional) The README suggested loading `rules_pods` with `http_archive` instead of `git_repository`…this is fairly unusual, so I changed it to the more common `git_repository`.~  < (I realized we can't recommend this because the repository doesn't version the compiled Swift binaries…)
> Bazel, rules_swift, and rules_apple updates

- Makefile
- Without this we could create a broken release if the binaries are not
already created or if the binaries are from an older commit.
> Build for release before archiving for Github Releases

- IntegrationTests/GoldMaster/Braintree.podspec.json.goldmaster
- IntegrationTests/GoldMaster/Calabash.podspec.json.goldmaster
- IntegrationTests/GoldMaster/FBSDKCoreKit.podspec.json.goldmaster
- IntegrationTests/GoldMaster/FolioReaderKit.podspec.json.goldmaster
- IntegrationTests/GoldMaster/GoogleAppIndexing.podspec.json.goldmaster
- IntegrationTests/GoldMaster/GoogleAuthUtilities.podspec.json.goldmaster
- IntegrationTests/GoldMaster/GoogleSignIn.podspec.json.goldmaster
- IntegrationTests/GoldMaster/OnePasswordExtension.podspec.json.goldmaster
- IntegrationTests/GoldMaster/PaymentKit.podspec.json.goldmaster
- IntegrationTests/GoldMaster/React.0.57.0.podspec.json.goldmaster
- IntegrationTests/GoldMaster/SFHFKeychainUtils.podspec.json.goldmaster
- IntegrationTests/GoldMaster/SevenSwitch.podspec.json.goldmaster
- IntegrationTests/GoldMaster/Stripe.podspec.json.goldmaster
- IntegrationTests/GoldMaster/UICollectionViewLeftAlignedLayout.podspec.json.goldmaster
- IntegrationTests/GoldMaster/iOSSnapshotTestCase.podspec.json.goldmaster
- IntegrationTests/GoldMaster/iRate.podspec.json.goldmaster
- IntegrationTests/GoldMaster/youtube-ios-player-helper.podspec.json.goldmaster
- Sources/PodToBUILD/BuildFile.swift
- Sources/PodToBUILD/ObjcLibrary.swift
- Sources/PodToBUILD/SwiftLibrary.swift
- objc_bundle is now apple_bundle_import
- Bundles and resources are passed through the `data` value of
objc_library
- Added function to optionally add load statements based on the types of
skylark nodes in the build files (swift, apple resource bundles, etc)
- Verify app bundles still copy resources to the same locations
- Make sure bundles are passed to SwiftLibrary correctly as well
> Updates for rules_apple resource rules

- .travis.yml
- Examples/BasiciOS/WORKSPACE
- Examples/Example.Makefile
- Makefile
- Package.resolved
- Tests/BuildTests/BuildTest.swift
- WORKSPACE
- tools/bazelwrapper
The goal with this is to update the dependencies to include  This updates the `rules_apple` dependency to latest in order to pull in https://github.com/bazelbuild/rules_swift/commit/19db162c614af9c9db354e14d68965c8eb58e348 and allow compiling with Xcode 10.2. This also switches to using the version of `rules_swift` included by `rules_apple`, rather than manually specifying it.
Finally, this upgrades the version of Bazel being used to be compatible with the newer versions of `rules_apple` and `rules_swift`.
This seems like it partially addresses https://github.com/pinterest/PodToBUILD/issues/74, but that also mentions other tasks like updating other projects and CI.
> Update Apple/Swift/Bazel versions to allow building with Xcode 10.2

- Sources/PodToBUILD/ShellContext.swift
- bin/update_pods.py
The current implementation of `tmpdir` just returns the root of the
user's global temp dir (as returned by `NSTemporaryDirectory()`). This
changes that to create a unique subdirectory within it. This means that
each invocation of `tmpdir` will now return a new, empty directory.
This helps avoid issues with output from one repository affecting
another repository. In particular when unzipping an archive from GitHub
I was seeing issues where `unzip` was asking whether `.gitignore` should
be overwritten and immediately failing with an EOF. This should provide
better isolation between repositories.
While I'm here, this also changes a rouge tab to spaces in a Python file.
> Use fresh temporary directories

- Sources/RepoToolsCore/RepoActions.swift
At least on macOS 10.14.4, this `tar` invocation prints each of the files it is unpacking to stderr. It seems that nothing is actually reading the stderr pipe from this subprocess, and it therefore deadlocks and never finishes when untarring a repo with many files. This can be reproduced with the latest stable PodToBUILD and both Bazel 0.24.1 and 0.25.2 via the following WORKSPACE file (and, say, running `bazel query @React//...`):
```bzl
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
name = "rules_pods",
urls = ["https://github.com/pinterest/PodToBUILD/releases/download/0.22.0-ee8466e/PodToBUILD.zip"],
)
load("@rules_pods//BazelExtensions:workspace.bzl", "new_pod_repository")
new_pod_repository(
name = "React",
url = …
```
> Suppress stderr when untarring

- BazelExtensions/workspace.bzl
PodToBUILD currently works by distributing a Darwin binary, which won't work on non-macOS platforms (like Linux). This is mainly an issue in non-vendored mode in a Bazel workspace shared with other, non-Apple targets. This change makes it easier for those setups by allowing the repositories to at least be loaded, even if they don't have valid content on those platforms.
In particular, this allows running `bazel query //...` on linux in a Bazel workspace that uses `new_pod_repository`.
> No-op on non-macOS platforms

- Sources/RepoToolsCore/RepoActions.swift
This expands the list of file extensions that are considered tarballs to include `.tar` and `.tgz`.
This is a quicker, less controversial change while https://github.com/pinterest/PodToBUILD/pull/80 is in PR.
> Add 'tar' and 'tgz' as valid tar.gz extensions

- Sources/RepoToolsCore/RepoActions.swift
When we populate the `pod_support` directories, we put all the headers (or rather symlinks to them) in the same directory together. This means that if there are multiple headers that share a basename, only one can end up in a given directory. Previously which one was determined by the result of glob and set iteration ordering, both of which are non-deterministic (differ per run and/or machine). This sorts those headers before symlinking to guarantee that the same symlinks end up "winning out" and being used on all machines. This allows remote cache sharing/hits between machines.
> Make pod_support headers more deterministic

- Sources/RepoToolsCore/RepoActions.swift
This allows the file-type determination to correctly ignore the fragment (part after the `#`) in the URL, plus it's more correct, since the URL *isn't* a file path.
> Treat download links as non-file URLs

- BazelExtensions/extensions.bzl
- IntegrationTests/Acknowlegements/BUILD.bazel
- IntegrationTests/Acknowlegements/acknowledgement1.plist
- IntegrationTests/Acknowlegements/acknowledgement2.plist
- IntegrationTests/RunTests.sh
- We cannot use `run_shell` without specifying a "command", switch to
just "run"
- Add integration test so this continues to be tested
> Fix acknowlegments plist generation

- IntegrationTests/GoldMaster/FBSDKCoreKit.podspec.json.goldmaster
- IntegrationTests/GoldMaster/GoogleAppIndexing.podspec.json.goldmaster
- IntegrationTests/GoldMaster/GoogleSignIn.podspec.json.goldmaster
- IntegrationTests/GoldMaster/OnePasswordExtension.podspec.json.goldmaster
- IntegrationTests/GoldMaster/Stripe.podspec.json.goldmaster
- IntegrationTests/GoldMaster/iRate.podspec.json.goldmaster
- IntegrationTests/GoldMaster/youtube-ios-player-helper.podspec.json.goldmaster
- Sources/PodToBUILD/BuildFile.swift
The `rules_apple` repo made a change (https://github.com/bazelbuild/rules_apple/commit/c6d0b2ceda2b7596005f6efc67546b309261e96e) which removes the `objc` provider from `apple_bundle_import`, enforcing that this is included via `data` rather than `deps`. Generated `apple_bundle_import` rules have been in both `data` and `deps` via PodToBUILD for a while, but now that they're no longer allowed in `deps` this ensures they don't end up there (but that they do make it into the generated file output).
> Don't put resource bundles in `deps` to comply with newer `rules_apple`

- BazelExtensions/workspace.bzl
- README.md
This allows a podspec to be checked into the repo, rather than only
allowing an external URL as a podspec.
> Add a podspec_file attribute

- BUILD
- Sources/PodToBUILD/Alias.swift
- Sources/PodToBUILD/BazelConstants.swift
- Sources/PodToBUILD/BuildFile.swift
- Sources/PodToBUILD/BuildOptions.swift
- Sources/PodToBUILD/GlobUtils.swift
- Sources/PodToBUILD/ObjcLibrary.swift
- Sources/PodToBUILD/RuleUtils.swift
- Sources/RepoToolsCore/RepoActions.swift
- bin/update_pods.py
Adds the ability to handle "child pods" within a pod. In cocoapods, its
possible to provide a path within another pod, and this doesn't map to
any notion we have. Simply put, it generates a BUILD file in the parent
directory, and aliases the Vendor/__POD__ to the parent directory.
Additionally, it has a first pass at handling adjacent, child or top
level pods. When there are 2 adjacent podspecs, cocoapods effectively
merges these into a single file. The first pass at this ability is
achieved by concatting build files together. Some algorithms rely on
having all the data structures around, so we'll need to update it to
merge build files at a higher level in the stack, and this is much more
complex.
There's a few cleanups around `EmptyBuildOptions` as it was tedious to
keep updating new …
> Support nested pods, or pods inside of a pod

- Package.swift
- Sources/PodToBUILD/ObjcLibrary.swift
- Sources/PodToBUILD/UserConfigurable.swift
- update to swift tools 5.0 to get supported platforms.
- macos 10.12 became the minimum requirement with https://github.com/pinterest/PodToBUILD/pull/96
- Fix some Swift4 string stuff.
- use `let` where compiler suggests it.
> fix warnings and errors when building on catalina with xcode 11.2.1

- Sources/PodToBUILD/UserConfigurable.swift
- Tests/PodToBUILDTests/UserConfigurableTests.swift
Basically do not assume there is only one ".". Take the item before the "." as the key, and the remainder of the string is the value.
> Preserve any . in the values uses for copts

- Sources/PodToBUILD/UserConfigurable.swift
- Tests/PodToBUILDTests/UserConfigurableTests.swift
Do this by only trimming whitespace, which will limit it to the start and end of the string.
> Preserve spaces in copts values

- Examples/Example.Makefile
- Makefile
The build tests were missing override_repository, which required a hack.
Instead, override the repository directly.
Additionally, it adds a command to `gen_workspace` for testing purposes
> Remove workaround for build test issue

- Examples/ChildPodspec/.gitignore
- Examples/ChildPodspec/Pods.WORKSPACE
- Examples/ChildPodspec/WORKSPACE
- Examples/Example.Makefile
- Sources/PodToBUILD/Lockfile.swift
- Sources/PodToBUILD/Workspace.swift
- bin/update_pods.py
- Load deps from `PODS` if necessary
- Build RepoTools before workspace gen
- Clear out pods only if the dir starts with http
- Add a workspace file
> Misc issues for workspace gen

- Sources/PodToBUILD/MultiPlatform.swift
- Sources/PodToBUILD/ObjcLibrary.swift
- Sources/RepoToolsCore/RepoActions.swift
For when we don't use a headermap, we use this instead. The current code
added a few less directories than the original code.
Additionally, it cleans up the algorithms to use `trivialize:`
> Cleanup header symlinking

- IntegrationTests/GoldMaster/BUILD
- Sources/PodToBUILD/BuildFile.swift
At some point, Bazel started rejecting resources in `deps` which was
recently added. This caused an issue in 3.4.1
> Filter resources from extra deps

- BazelExtensions/extensions.bzl
- IntegrationTests/GoldMaster/ObjcParentWithSwiftSubspecs.podspec.json.goldmaster
- Sources/PodToBUILD/SwiftLibrary.swift
In order to use `expand_location` we need to have a dep on the input.
https://docs.bazel.build/versions/master/skylark/lib/ctx.html#expand_location
Private module maps used in swift library that were previously not
`deps`, and they are specified now specified as header, so they remain
private. If we fix `swiftc_inputs` to be expandable in Bazel this would
be unnecessary.
For xcode project generation we need to call `expand_location` and the
aspect will fail if it doesn't have it as a dep. The corresponding code is added
to Tulsi and XCHammer https://github.com/bazelbuild/tulsi/pull/157
> Allow the replacement of execpath

- Sources/PodToBUILD/SwiftLibrary.swift
When we `enableHeaderMap`, this is required to be a dependency. Note:
that this is a workaround for an issue with Bazel not including
`swiftc_inputs` as a pre-requisite
> Adds headermap as a dep

- BazelExtensions/extensions.bzl
Beyond the initial done in #174, we also need to include 'headers' in
the generated CcCompilationContext and return a CcInfo provider with our
headermap generation rule.
See: https://github.com/bazelbuild/bazel/issues/10674
> Improve CcInfo parity with ObjcProvider

- BazelExtensions/workspace.bzl
- README.md
- bin/update_pods.py
We use the name 'sdkFrameworks' in the internal Swift code, but all
PodToBUILD users should spell this as 'sdk_frameworks' in Bazel-land.
> Spell 'sdk_frameworks' as expected

- Examples/FBSDK/WORKSPACE
- Examples/SwiftSubspec/WORKSPACE
- IntegrationTests/GoldMaster/ObjcParentWithSwiftSubspecs.podspec.json.goldmaster
- Sources/ObjcSupport/include/module.modulemap
- Sources/PodToBUILD/Skylark.swift
- Sources/PodToBUILD/SwiftLibrary.swift
- WORKSPACE
Required by rules_swift 0.24.0, when generated_header_name is provided, generates_header has to be set to True.
Updated versions of other rules dependencies and examples/tests as well.
> Set generates_header when generated_header_name is provided

- Sources/RepoToolsCore/RepoActions.swift
Add support to tar.xz; close #108 
You can see some information about this file from [cocoapods-downloader](https://github.com/CocoaPods/cocoapods-downloader/blob/1.6.3/lib/cocoapods-downloader/remote_file.rb) on lines 69 and 96
> Support tar.xz and txz
